logger: wandb
project: gpt2

run_name: gpt-j-base-dialog
learning_rate: 3e-4
num_epochs: 3
batch_size: 4
accumulate_grad_batches: 2
block_size: 1024
logging_steps: 10

model_name: heegyu/kogpt-j-base
revision: main
from_flax: false
data_dir: /data2/dialog-v1-vocab51k-block1024/train
eval_data_dir: /data2/dialog-v1-vocab51k-block1024/test
cache_dir: /data2/.cache
output_dir: /data2/checkpoint
