logger: wandb
project: gpt2

run_name: test
learning_rate: 5e-5
num_epochs: 1
batch_size: 1
accumulate_grad_batches: 32
max_steps: 1000000
save_steps: 50000
block_size: 1024

model_name: heegyu/kogpt-j-base
data_dir: /data2/
accelerator: tpu
devices: 8
# accelerator: cpu
# devices: 1