python3 train_clm_flax.py \
    --output_dir="checkpoint/kogpt2-base-v2" \
    --model_type="gpt2" \
    --config_name="gpt2" \
    --tokenizer_name="gpt2" \
    --dataset_name="heegyu/kowikitext" \
    --dataset_config_name="20221001" \
    --do_train \
    --block_size="512" \
    --per_device_train_batch_size="4" \
    --per_device_eval_batch_size="4" \
    --learning_rate="5e-3" --warmup_steps="1000" \
    --adam_beta1="0.9" --adam_beta2="0.98" --weight_decay="0.01" \
    --overwrite_output_dir \
    --num_train_epochs="1" \
    --logging_steps="500" \
    --save_steps="2500"